apiVersion: skaffold/v4beta13
kind: Config

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ai-orchestration-server
      context: ai-orchestration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: src
            src:  /home/app

    - image: router
      context: sandbox/router
      docker:
        dockerfile: Dockerfile

    - image: sandbox-server
      context: sandbox/server
      docker:
        dockerfile: Dockerfile

    - image: template
      context: sandbox/template
      docker:
        dockerfile: Dockerfile

    - image: agent
      context: sandbox/agent
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    # - k8s/rbac.yml
    - k8s/ai-deployment.yml
    - k8s/ai-service.yml
    - k8s/router-deployment.yml
    - k8s/router-service.yml
    - k8s/sandbox-deployment.yml
    - k8s/sandbox-service.yml
    - k8s/sandbox-configmap.yml
    - k8s/ingress.yml
