apiVersion: apps/v1
kind: Deployment
metadata:
  name:  router-server-deployment
  labels:
    name:  router-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  router
  template:
    metadata:
      labels:
        app:  router
    spec:
      containers:
      - image:  router
        name:  router-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "5000m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /api/v1/status/healthz
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/status/readyz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10     
        ports:
        - containerPort:  3000
          name:  router-port
